<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerUskzRRN\srcApp_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerUskzRRN/srcApp_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerUskzRRN.legacy');

    return;
}

if (!\class_exists(srcApp_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerUskzRRN\srcApp_KernelDevDebugContainer::class, srcApp_KernelDevDebugContainer::class, false);
}

return new \ContainerUskzRRN\srcApp_KernelDevDebugContainer([
    'container.build_hash' => 'UskzRRN',
    'container.build_id' => '4e43c422',
    'container.build_time' => 1578993279,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerUskzRRN');
